Traceback (most recent call last):
  File "/disk/u/lofty/GPTNext/experiments/_05_int8_train.py", line 127, in <module>
    data_dir = os.path.join('../data', dataset); assert os.path.exists(data_dir)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
